/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-03-12 18:35:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.*;
import java.util.*;
import com.product.*;
import com.customer.*;
import java.sql.*;
import com.databaseconnection.*;

public final class products_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/includes/head.jsp", Long.valueOf(1646815743117L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1646544286766L));
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1647110121752L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.product");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.customer");
    _jspx_imports_packages.add("com.databaseconnection");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");

	ProductConn pcon=new ProductConn();
	List<Product> products=pcon.all_Product_Details();
	ArrayList<Cart> cart_list = (ArrayList<Cart>) session.getAttribute("cart-list");
	if (cart_list != null) {
		request.setAttribute("cart_list", cart_list);
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css\">\r\n");
      out.write("	\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color:#fff;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write(".topnav{\r\n");
      out.write("	 color: #fff;\r\n");
      out.write("	 text-align:center;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul{\r\n");
      out.write("	display:inline-flex;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	color:#fff;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul li {\r\n");
      out.write("	width:150px;\r\n");
      out.write("	margin:5px;\r\n");
      out.write("	padding:10px;\r\n");
      out.write("	}\r\n");
      out.write(".topnav ul li a {\r\n");
      out.write("  color:black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("  background-color:#04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a.active {\r\n");
      out.write("  background-color: #04AA6D;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".sub-menu1{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul li:hover .sub-menu1{\r\n");
      out.write("	display:block;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	background:#fff;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	margin-left: -30px;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul li:hover .sub-menu1 ul{\r\n");
      out.write("	display:block;\r\n");
      out.write("	margin:-10px;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul li:hover .sub-menu1 ul li{\r\n");
      out.write("	 width:150px;\r\n");
      out.write("	 padding:5px;\r\n");
      out.write("	 background: transparent;\r\n");
      out.write("	 //border-radius: 3px;\r\n");
      out.write("	 text-align: left;\r\n");
      out.write("}\r\n");
      out.write(".topnav ul li:hover .sub-menu1 ul li :last-child{\r\n");
      out.write("	border-bottom: none;\r\n");
      out.write("	}\r\n");
      out.write(".topnav ul li:hover .sub-menu1 ul li a:hover{\r\n");
      out.write("	//color:blue;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write(".sub-menu2{\r\n");
      out.write("	display:none;\r\n");
      out.write("}\r\n");
      out.write(".hover-me:hover .sub-menu2{\r\n");
      out.write("	position:absolute;\r\n");
      out.write("	display:block;\r\n");
      out.write("	margin-top:-20px;\r\n");
      out.write("	margin-left:140px;\r\n");
      out.write("	background:#fff;\r\n");
      out.write("}\r\n");
      out.write(".img img{\r\n");
      out.write("	width:100%;\r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  //border: 1px solid red;\r\n");
      out.write("  display:block;\r\n");
      out.write("}\r\n");
      out.write(".img img1{\r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  //border: 1px solid red;\r\n");
      out.write("  display:block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    ");
String email=(String)session.getAttribute("uname"); 
      out.write("\r\n");
      out.write("<div class=\"container-fluid p-3 bg-primary text-white text-center\">\r\n");
      out.write("<form  method=\"post\">\r\n");
      out.write("  <input type=\"search\"  name=\"search\" placeholder=\"Search \"><button type=\"submit\"formaction=\"search.jsp\"><i class=\"bi bi-search\"></i>Search</button></\r\n");
      out.write("  </form>\r\n");
      out.write(" <a href=\"products.jsp\" class=\"text-white p-3\">Home</a>\r\n");
      out.write(" <a href=\"loginpage.jsp\"class=\"text-white p-3\">Login</a>\r\n");
      out.write(" <a href=\"\" style=\"color:white\">");
out.println(email);
      out.write("</a>\r\n");
      out.write("<a href=\"LogOutServlet\"class=\"text-white p-3\">logout</a>\r\n");
      out.write("<a href=\"cart.jsp\" class=\"text-white p-3 text-decoration:none\">Cart <span class=\"badge badge-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartProduct.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a><i class=\"bi bi-cart-fill\"></i>\r\n");
      out.write("<a href=\"order.jsp\"class=\"text-white p-3\">Orders</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"topnav\">\r\n");
      out.write("<ul>\r\n");
      out.write("<li><a class=\"active\" href=\"products.jsp\"><i class=\"bi bi-house\"></i>Home</a></li>\r\n");
      out.write("<li><a href=\"grocery.jsp\">Grocery</a></li>\r\n");
      out.write("<li><a href=\"\">Mobiles</a></li>\r\n");
      out.write("<li><a href=\"\">Fashion <i class=\"bi bi-arrow-down-short\"></i></a>\r\n");
      out.write("	<div class=\"sub-menu1\">\r\n");
      out.write("		<ul>\r\n");
      out.write("		<li class=\"hover-me\"><a href=\"#\">Men's Top Wear<i class=\"bi bi-arrow-right-short\"></i></a>\r\n");
      out.write("			<div class=\"sub-menu2\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"fashion.jsp\">All</a></li>\r\n");
      out.write("				<li><a href=\"#\">Shirts</a></li>\r\n");
      out.write("				<li><a href=\"#\">Tea Shirts</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li class=\"hover-me\"><a href=\"#\">Men's Bottom Wear <i class=\"bi bi-arrow-right-short\"></i></a>\r\n");
      out.write("		<div class=\"sub-menu2\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"fashion.jsp\">All</a></li>\r\n");
      out.write("				<li><a href=\"#\">jeans</a></li>\r\n");
      out.write("				<li><a href=\"#\">tracks</a></li>\r\n");
      out.write("				<li><a href=\"#\">boxers</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a href=\"#\">Women Ethnic</a></li>\r\n");
      out.write("		<li><a href=\"#\">Women Western</a></li>\r\n");
      out.write("		<li><a href=\"#\">men's Footwear</a></li>\r\n");
      out.write("		<li><a href=\"#\">Womens Footwear</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"electonics.jsp\">Eletronics <i class=\"bi bi-arrow-down-short\"></i></a>\r\n");
      out.write("	<div class=\"sub-menu1\">\r\n");
      out.write("		<ul>\r\n");
      out.write("		<li class=\"hover-me\"><a href=\"#\">audio<i class=\"bi bi-arrow-right-short\"></i></a>\r\n");
      out.write("			<div class=\"sub-menu2\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"electonics.jsp\">All</a></li>\r\n");
      out.write("				<li><a href=\"#\">Ear phones</a></li>\r\n");
      out.write("				<li><a href=\"#\">Speakers</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		<li><a href=\"#\">Laptop Accessories</a></li>\r\n");
      out.write("		<li><a href=\"#\">Computer Peripherals</a></li>\r\n");
      out.write("		<li><a href=\"#\">Gaming</a></li>\r\n");
      out.write("		<li><a href=\"#\">Powerbank</a></li>\r\n");
      out.write("		<li><a href=\"#\">MobileAccessory</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"furinture.jsp\">Furniture</a></li>\r\n");
      out.write("<li> <a href=\"applince.jsp\">Home Appliances</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("	");
String msg=request.getParameter("msg"); 
		if("done".equals(msg)){
	
      out.write("\r\n");
      out.write("	<h3>Cart Added Successfully</h3>\r\n");
      out.write("	");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
if("notexist".equals(msg)){
		
      out.write("\r\n");
      out.write("		<h3>item is not available to cart</h3>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("		<div class=\"card-header my-3\">All Products</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");

			if (!products.isEmpty()) {
				for (Product p : products) {
			
      out.write("\r\n");
      out.write("			<div class=\"col-md-3 my-3\">\r\n");
      out.write("				<div class=\"card w-100\">\r\n");
      out.write("					<img class=\"card-img-top\" src=\"./images/");
      out.print(p.getImage() );
      out.write("\"\r\n");
      out.write("						alt=\"Card image cap\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<h5 class=\"card-title\">");
      out.print(p.getProduct_name());
      out.write("</h5>\r\n");
      out.write("						<h6 class=\"price\">Price: $");
      out.print(p.getProduct_price() );
      out.write("</h6>\r\n");
      out.write("						<div class=\"mt-3 d-flex justify-content-between\">\r\n");
      out.write("							<a class=\"btn btn-dark\" href=\"Add_To_Cart?id=");
      out.print(p.getProduct_id());
      out.write("\">Add to Cart</a> <a\r\n");
      out.write("								class=\"btn btn-primary\" href=\"order-now?quantity=1&id=");
      out.print(p.getProduct_id());
      out.write("\">Buy Now</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			} else {
			out.println("There is no proucts");
			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
